resources:
- namespace.yaml
- database.yaml
- redis.yaml
- frontend.yaml
- keygen.yaml
- distgit.yaml
- resalloc.yaml
- backend.yaml
- ingress.yaml
- secrets.yaml
commonLabels:
  app: copr
configMapGenerator:
- files:
  - initdb.sh=config/database/initdb.sh
  name: copr-database
- files:
  - httpd.conf=config/frontend/httpd.conf
  name: copr-frontend
- files:
  - copr-keygen.conf=config/keygen/copr-keygen.conf
  name: copr-keygen
- files:
  - pools.yaml=config/resalloc/pools.yaml
  - builder_config=config/backend/.ssh/builder_config
  - local-new-aarch64=config/resalloc/local-new-aarch64
  - local-new-x86=config/resalloc/local-new-x86
  name: copr-resalloc
- files:
  - builder_config=config/backend/.ssh/builder_config
  name: copr-backend
namespace: fedora-copr
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# database image
# redis image
# resalloc image
# distgit image
# keygen image
# frontend image
# builder image
# backend image
images:
- digest: sha256:957c96d41992da590421bcc6ed235e79959b3d183c838874cdf6e8965355263c
  name: pkking/copr_backend
- digest: sha256:8432e2f09b06e7351150d21e79091e6e280e3b2cdddc524ae31373eb3703a0e7
  name: pkking/copr_backend_httpd
- digest: sha256:c767a1929b65e355bc627768bbe4bb5434628846ba3f923d129accd970add517
  name: pkking/copr_database
- digest: sha256:822c54bbe321aa73a6c0cb6d51977c462ab5b3b14ef2f15ad17665c51ee601d2
  name: pkking/copr_distgit
- digest: sha256:67f662408fc76fccde44937ec16986e90f4075e7c4976f86b65f023579126839
  name: pkking/copr_frontend
- digest: sha256:1fcffd14fbf8a527a4bec2bc871e62e0deba80d9049667e56eb31e92b031783c
  name: pkking/copr_keygen-signd
- digest: sha256:04476c143a231e2dab2a4256a39415a2d5905f16c4fc6d7225d9d99d8b8e390d
  name: pkking/copr_resalloc
